const products = [
    {
        name: "Lenovo comp product1",
        description: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
        count: 5,
        price: 100,
        category: "Computers/Laptops",
        images: [
            { path: "/images/games-category.png"},
            { path: "/images/monitors-category.png"},
            { path: "/images/tablets-category.png"},
        ],
        rating: 5,
        reviewsNumber: 5,
        reviews: [],
        attrs: [{ key: "color", value: "blue"}],
    },
    {
        name: "Lenovo comp product2",
        description: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
        count: 5,
        price: 100,
        category: "Computers/Laptops",
        images: [
            { path: "/images/games-category.png"},
            { path: "/images/monitors-category.png"},
            { path: "/images/tablets-category.png"},
        ],
        rating: 3,
        reviewsNumber: 5,
        reviews: [],
        attrs: [{ key: "color", value: "blue"}],
    },
    {
        name: "Lenovo comp product3",
        description: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
        count: 5,
        price: 100,
        category: "Computers/Laptops",
        images: [
            { path: "/images/games-category.png"},
            { path: "/images/monitors-category.png"},
            { path: "/images/tablets-category.png"},
        ],
        rating: 4,
        reviewsNumber: 5,
        reviews: [],
        attrs: [{ key: "color", value: "blue"}],
    },
    {
        name: "Lenovo comp product4",
        description: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
        count: 5,
        price: 200,
        category: "Computers/Laptops",
        images: [
            { path: "/images/games-category.png"},
            { path: "/images/monitors-category.png"},
            { path: "/images/tablets-category.png"},
        ],
        rating: 5,
        reviewsNumber: 5,
        reviews: [],
        attrs: [{ key: "color", value: "blue"}],
    },
    {
        name: "Lenovo comp product5",
        description: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
        count: 5,
        price: 150,
        category: "Computers/Laptops",
        images: [
            { path: "/images/games-category.png"},
            { path: "/images/monitors-category.png"},
            { path: "/images/tablets-category.png"},
        ],
        rating: 5,
        reviewsNumber: 5,
        reviews: [],
        attrs: [{ key: "color", value: "red"}],
    },
    {
        name: "Lenovo comp product6",
        description: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
        count: 5,
        price: 100,
        category: "Computers/Laptops",
        images: [
            { path: "/images/games-category.png"},
            { path: "/images/monitors-category.png"},
            { path: "/images/tablets-category.png"},
        ],
        rating: 2,
        reviewsNumber: 5,
        reviews: [],
        attrs: [{ key: "color", value: "blue"}],
    },
    
];

module.exports = products;